<?php

namespace HomeBundle\Entity;

/**
 * carouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carouselRepository extends \Doctrine\ORM\EntityRepository
{
}
